/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moraisparker.visao;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import moraisparker.controle.MenuPrincipalController;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import moraisparker.modelos.Funcionario;

/**
 *
 * @author Desktop
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    private final MenuPrincipalController controller;
    private Funcionario funcionario;
    
    public JanelaPrincipal(Funcionario funcionarioAutenticado) {
        initComponents();
        this.controller =  new MenuPrincipalController(this);
        this.funcionario = funcionarioAutenticado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        labelCargo = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuEstacionamento = new javax.swing.JMenu();
        menuMonitorar = new javax.swing.JMenuItem();
        menuProprietario = new javax.swing.JMenuItem();
        menuVeiculo = new javax.swing.JMenuItem();
        menuEventos = new javax.swing.JMenuItem();
        menuOcorrecias = new javax.swing.JMenuItem();
        menuBlocosEstacionamentos = new javax.swing.JMenuItem();
        menuFuncionario = new javax.swing.JMenu();
        menuRelatorios = new javax.swing.JMenu();
        menuConfiguracao = new javax.swing.JMenu();
        btnSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moraisparker/visao/imgs/sair-16x16.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairClicked(evt);
            }
        });

        labelCargo.setText("<html><b>[GESTOR]</b> Nome do Funcionário</html>");

        labelData.setForeground(new java.awt.Color(0, 0, 255));
        labelData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelData.setText("...");
        labelData.setFocusTraversalPolicyProvider(true);

        labelHora.setForeground(new java.awt.Color(0, 0, 255));
        labelHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHora.setText("...");
        labelHora.setFocusTraversalPolicyProvider(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(labelCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelData, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelData, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair)))
        );

        menuEstacionamento.setText("Estacionamento");

        menuMonitorar.setText("Monitorar");
        menuMonitorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMonitorarActionPerformed(evt);
            }
        });
        menuEstacionamento.add(menuMonitorar);

        menuProprietario.setText("Proprietários");
        menuProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProprietarioActionPerformed(evt);
            }
        });
        menuEstacionamento.add(menuProprietario);

        menuVeiculo.setText("Veículos");
        menuVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVeiculoActionPerformed(evt);
            }
        });
        menuEstacionamento.add(menuVeiculo);

        menuEventos.setText("Eventos");
        menuEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEventosActionPerformed(evt);
            }
        });
        menuEstacionamento.add(menuEventos);

        menuOcorrecias.setText("Ocorrências");
        menuOcorrecias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOcorreciasActionPerformed(evt);
            }
        });
        menuEstacionamento.add(menuOcorrecias);

        menuBlocosEstacionamentos.setText("Blocos de Estacionamento");
        menuBlocosEstacionamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBlocosEstacionamentosActionPerformed(evt);
            }
        });
        menuEstacionamento.add(menuBlocosEstacionamentos);

        jMenuBar1.add(menuEstacionamento);

        menuFuncionario.setText("Funcionários");
        menuFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuFuncionarioMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuFuncionario);

        menuRelatorios.setText("Relatórios");
        menuRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRelatoriosMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuRelatorios);

        menuConfiguracao.setText("Configurações");
        menuConfiguracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuConfiguracaoMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuConfiguracao);

        btnSobre.setText("Sobre");
        btnSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(549, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(816, 638));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairClicked
        this.controller.navegarParaLogin();
        this.dispose();
        
    }//GEN-LAST:event_btnSairClicked

    private void menuProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProprietarioActionPerformed
        if (menuProprietario.isEnabled()){
            this.controller.navegarParaProprietarios();
        }
    }//GEN-LAST:event_menuProprietarioActionPerformed

    private void menuVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVeiculoActionPerformed
        if (menuVeiculo.isEnabled()) {
            this.controller.navegarParaVeiculos();
        }
    }//GEN-LAST:event_menuVeiculoActionPerformed

    private void menuMonitorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMonitorarActionPerformed
        if (menuMonitorar.isEnabled()){
            this.controller.navegarParaMonitorar();
        }
    }//GEN-LAST:event_menuMonitorarActionPerformed

    private void menuEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEventosActionPerformed
        if (menuEventos.isEnabled()){
            this.controller.navegarParaEventos();
        }
    }//GEN-LAST:event_menuEventosActionPerformed

    private void menuOcorreciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOcorreciasActionPerformed
        if (menuOcorrecias.isEnabled()){
            this.controller.navegarParaOcorrencias();
        }
    }//GEN-LAST:event_menuOcorreciasActionPerformed

    private void menuRelatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRelatoriosMouseClicked
        if(menuRelatorios.isEnabled()){
            this.controller.navegarParaRelatórios();
        }
    }//GEN-LAST:event_menuRelatoriosMouseClicked

    private void btnSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSobreMouseClicked
        if (btnSobre.isEnabled()){
            this.controller.navegarParaSobre();
        }
    }//GEN-LAST:event_btnSobreMouseClicked

    private void menuBlocosEstacionamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBlocosEstacionamentosActionPerformed
        if (menuBlocosEstacionamentos.isEnabled()){
            this.controller.navegarParaEstacionamentos();
        }
    }//GEN-LAST:event_menuBlocosEstacionamentosActionPerformed

    private void menuFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFuncionarioMouseClicked
        if (menuFuncionario.isEnabled()){
            this.controller.navegarParaFuncionarios();
        }
    }//GEN-LAST:event_menuFuncionarioMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        labelCargo.setText("<html><p style='color: blue'><span style='color:red'>["+this.funcionario.getCategoria()+"]</span> "+funcionario.getNome()+"</p><html>");
        //Data
       Date dataSistema = new Date();
       SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
       labelData.setText(formato.format(dataSistema));
       
       //Hora
       Timer timer = new Timer(1000, new hora());
       timer.start();
       
    }//GEN-LAST:event_formWindowOpened

    private void menuConfiguracaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuConfiguracaoMouseClicked
        this.controller.navegarParaconfiguracao();
    }//GEN-LAST:event_menuConfiguracaoMouseClicked
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JMenu btnSobre;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCargo;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelHora;
    private javax.swing.JMenuItem menuBlocosEstacionamentos;
    private javax.swing.JMenu menuConfiguracao;
    private javax.swing.JMenu menuEstacionamento;
    private javax.swing.JMenuItem menuEventos;
    private javax.swing.JMenu menuFuncionario;
    private javax.swing.JMenuItem menuMonitorar;
    private javax.swing.JMenuItem menuOcorrecias;
    private javax.swing.JMenuItem menuProprietario;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenuItem menuVeiculo;
    // End of variables declaration//GEN-END:variables

    public JMenu getMenuEstacionamento() {
        return menuEstacionamento;
    }

    public void setMenuEstacionamento(JMenu menuEstacionamento) {
        this.menuEstacionamento = menuEstacionamento;
    }

    public JMenuItem getMenuEventos() {
        return menuEventos;
    }

    public void setMenuEventos(JMenuItem menuEventos) {
        this.menuEventos = menuEventos;
    }

    public JMenu getMenuFuncionario() {
        return menuFuncionario;
    }

    public void setMenuFuncionario(JMenu menuFuncionario) {
        this.menuFuncionario = menuFuncionario;
    }

    public JMenuItem getMenuMonitorar() {
        return menuMonitorar;
    }

    public void setMenuMonitorar(JMenuItem menuMonitorar) {
        this.menuMonitorar = menuMonitorar;
    }

    public JMenuItem getMenuOcorrecias() {
        return menuOcorrecias;
    }

    public void setMenuOcorrecias(JMenuItem menuOcorrecias) {
        this.menuOcorrecias = menuOcorrecias;
    }

    public JMenuItem getMenuProprietario() {
        return menuProprietario;
    }

    public void setMenuProprietario(JMenuItem menuProprietario) {
        this.menuProprietario = menuProprietario;
    }

    public JMenu getMenuRelatorios() {
        return menuRelatorios;
    }

    public void setMenuRelatorios(JMenu menuRelatorios) {
        this.menuRelatorios = menuRelatorios;
    }

    public JMenuItem getMenuVeiculo() {
        return menuVeiculo;
    }

    public void setMenuVeiculo(JMenuItem menuVeiculo) {
        this.menuVeiculo = menuVeiculo;
    }

    public JMenuItem getMenuBlocosEstacionamentos() {
        return menuBlocosEstacionamentos;
    }

    public void setMenuBlocosEstacionamentos(JMenuItem menuBlocosEstacionamentos) {
        this.menuBlocosEstacionamentos = menuBlocosEstacionamentos;
    }

    public JLabel getLabelData() {
        return labelData;
    }

    public void setLabelData(JLabel labelData) {
        this.labelData = labelData;
    }

    public JLabel getLabelHora() {
        return labelHora;
    }

    public void setLabelHora(JLabel labelHora) {
        this.labelHora = labelHora;
    }

    public Funcionario getFuncionario() {
        return funcionario;
    }

    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    
    

    class hora implements ActionListener {
        @Override
        public void actionPerformed (ActionEvent evt) {
            Calendar now = Calendar.getInstance();
            labelHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }
}
